config = {
    'init_scale': 0.1,
    'lr': .001,
    'lr_decay': 0.8,
    'max_epoch':7,
    'max_max_epoch':40,
    'max_grad_norm': 5,
    'num_layers': 1,
    'num_steps': 400,
    'embed_size': 300,
    'hidden_size':300,
    'keep_prob': 0.45,
    'batch_size': 32,
    'num_classes': 2,
    'vocab_size': 80000,
    'combine_mode': 'last',
    'weight_decay': 0e-8,
    'save_path': 'checkpoint/imdb/',
    'num_buckets':1
}
